# config/packages/security.yaml
security:
  # We don't need enable_authenticator_manager anymore since it's the default in Symfony 7

  # Providers (not needed if we're using a stateless token-based authentication without a user provider)
  providers:
    api_token_user_provider:
      memory:
        users:
          api_user:
            password: null
            roles: ["ROLE_API"]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # API firewall for stateless token-based authentication
    api:
      pattern: ^/api
      stateless: true
      custom_authenticator: App\Security\ApiTokenAuthenticator

  access_control:
    # Only allow access to API routes if the user has the role ROLE_API
    - { path: ^/api, roles: ROLE_API }
